### ISSUE TITLE
Move field_has_* from MAterial types into a single field

### ISSUE THREAD

**Issue by amitaibu** [Gizra/garmentbox#135]
List with [checkboxes](https://www.evernote.com/shard/s206/sh/179166b1-5710-4976-bbed-c205ea6a28a1/f8d0843c87246720716bc07948da2b5c)

**Comment by Moo64c** [comment]
Also fixing the exceptions and display bugs on the material page.

**Comment by Moo64c** [comment]
Closed (#140).
