### ISSUE TITLE
Material - Extra fields

### ISSUE THREAD

**Issue by bricel** [Gizra/garmentbox#16]
- Material type: Fabric/Trim/Button/Band/Other
- Width/Radius/Length,  of material.
- Optional : Washing instruction.
- Optional: Fabric content - example cotton 50% 

```
  @api
  Scenario: Basic content is shown on the item page.
    Given I am logged in as a user with the "authenticated user" role
    And I am on a "material" page titled "Ivory Satin Button"
    Then I should see the heading "Ivory Satin Button"
    And I should see "120cm"
    And I should see "Wash & Rinse"
    And I should see "cotton 50%"
```

**Comment by bricel** [comment]
Add 3 new fields to material content type.

**Comment by bricel** [comment]
1. Behat test.
2. Update content type and create new taxonomy.
3. Create a new migrate import to import new taxonomy. 
4. Update material migrate to import some measurment.

**Comment by bricel** [comment]
See my comments.
https://www.evernote.com/shard/s266/sh/18407c6d-366a-4a04-94c7-33940337e515/aad55d4c3f5b1480c9c1e07c65d7e07a

**Comment by Moo64c** [comment]
### Found something bizarre in the database:

Example BOM on an item with node ID 40:
![](http://img845.imageshack.us/img845/7663/s011.png)

#### Notice two anomalies:

###### For every value added, a new field collection is added.

###### Target ID added was 10 less then expected - for material with nid 58, "48" was added to the database.

#### The materials' data against the databases' data:

(These were closely followed to see what was added to the database).
![](http://img545.imageshack.us/img545/4479/s013.png)
![](http://img837.imageshack.us/img837/7906/s012.png)

![](http://img805.imageshack.us/img805/2590/s010.png)
![](http://img341.imageshack.us/img341/2959/s009.png)

**Comment by Moo64c** [comment]
[Closed.](https://github.com/Gizra/Garment-Box/pull/90#issuecomment-10927334)
