### ISSUE TITLE
Login, Request password design

### ISSUE THREAD

**Issue by bricel** [Gizra/garmentbox#181]
![Screenshot 12:30:12 3:43 PM](https://f.cloud.github.com/assets/165644/35859/542a31ba-5287-11e2-82c1-f99d3a5825eb.png)
Add design to login form, and reset password form

**Comment by amitaibu** [comment]
I think it is better to revert this - it includes the entire update which isn't fixed yet

‫ב-2 במרץ 2014, בשעה 22:00, ‏Brice Lenfant notifications@github.com כתב/ה:‬
