### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by ghost** [Gizra/garmentbox#24]
Unregistered users:
signup page

New registered users (with no seasons):
see issue: #28

Signed up users:
- Creat a "Current season" checkbox to  season content type
- Only one season can be marked as "current season"
- After login redirect to the season page marked as currnet season
- Add a dropdown select list on the right side with all the existsting season
- Selceting a season from this list will move to the selected season page

**Comment by bricel** [comment]
Marking the season with flag, using flag trim to make sure we only have one season flagged

**Comment by ghost** [comment]
If a user have only one season, redirect him anyway after login to this collection without dependency on the checkbox status

**Comment by ghost** [comment]
Given I am logged in as a user with the "authenticated user" role
When that I am on the homepage
Then redierect me to a  page titled "Autumn-Winter 2013 Women"

**Comment by bricel** [comment]
Please add this test
