### ISSUE TITLE
Production feature  

### ISSUE THREAD

**Issue by ghost** [Gizra/garmentbox#25]
Define in a doc following features.

Production order - consist of invetory line items for quatity production
cost, factory information.

*reference to order via inventory lines

Function - 
- 'Shopping list' all materials required for this production batch #22
- Cutters must batch print.  #64
- Shipping to factory material inventory report to add to boxes #65

https://docs.google.com/a/gizra.com/file/d/0B9aCsZwIPBGPWksxbkVLTVdub2s/edit

https://docs.google.com/a/gizra.com/document/d/1e_04JGw6VfK5zio5OGCAld3SDVGYBGUveim88N5oWjg/edit

**Comment by bitamar** [comment]
Use the form API to create the form and theme it into the table.

**Comment by bitamar** [comment]
Fixes: 
- Disable new IL quantity inputs when their check-box is not checked.
- Open links in _blank
- New ILs are only created on the first variant.
- Add a test for this ^
