### ISSUE TITLE
Add item form - Flow and Redirect

### ISSUE THREAD

**Issue by ghost** [Gizra/garmentbox#31]
- Change the save button to "Save and add an item variation"
- After clicking this button redirect to the "add item variation" form
- If a user doesn't create an item variation and close the form. redirect him to the item node view with the popup bubble (See #32).
- If the user create an item variation redirect him to the item page with the specific item variation tab selected.

**Comment by bitamar** [comment]
https://github.com/Gizra/Garment-Box/pull/50

**Comment by bitamar** [comment]
Merged.
