### ISSUE TITLE
Popup bubble content type

### ISSUE THREAD

**Issue by ghost** [Gizra/garmentbox#32]
Please create a popup content type that allows creating a poppu pointing to an element on a page according to spesific rules

**Comment by bricel** [comment]
A bit more info about this feature:
We want a simple way to add bubble content (Using http://drupal.org/project/beautytips)
Using a new content type (Help content) with the following fields:
- Bubble text 
- Element selector - The element(s) that the bubble will be attached to. 
- Bubble id - : This is like  a page visibility condition - (a class that will appear in the page body element).
- Display mode: Open, Closed, Hover.

Each plugin/ views  will be responsible to add its own bubble ids.

Framework for the module:
https://gist.github.com/6d0b6ad943eca14b9a83

Create a new module for this: garment_box_tooltips

**Comment by bricel** [comment]
We should check what is the best bubble module for this :
- http://drupal.org/project/websnapr
- http://drupal.org/project/beautytips
- http://drupal.org/project/qtip
- http://drupal.org/project/tipsy
