### ISSUE TITLE
Season and Item flow.

### ISSUE THREAD

**Issue by ghost** [Gizra/garmentbox#33]
- If a user has a season with no item redirect to season page with "Item" tab selected. popup*\* pointing to "add a new item" button with info text
- If a user have item but have no task list redirect to season page with "task list" tab. popup*\* pointing to "add new task" button with info text

*\* Related to issue #32

**Comment by bricel** [comment]
This is a temporary solution until we create the dashboard.

**Comment by bitamar** [comment]
What if there's an item that doesn't have any item-variants? In this case nothing is shown in the "items". Perhaps in this case we need to redirect to add-variant instead of to add task?

**Comment by ghost** [comment]
Not sure, i'm guessing that the creation on variants might take long... and that one of the first tasks can be... "try fabrics for blue dress...". 
Somehow i feel that variant is an advance stage in creating a collection. but one again, it's an assumption. @bricel what do you think?
