### ISSUE TITLE
Material dropdown list

### ISSUE THREAD

**Issue by ghost** [Gizra/garmentbox#36]
On material item name (see form: http://opengizra.com/www/item-instance/56#overlay=field-collection/field-bom-info/add/node/56%3Fdestination%3Dnode/56)  the list should show the material nick names instead of the titles

**Comment by bitamar** [comment]
Do you want to change the material title to nickname wherever it's shown, or only on a specific select list?

**Comment by ghost** [comment]
let's in the meanwhile change ot only in this select list

**Comment by bricel** [comment]
No need to change title. Just fix the double escaping issue on the name list.
