### ISSUE TITLE
Add new tab in season for line-sheet

### ISSUE THREAD

**Issue by bricel** [Gizra/garmentbox#80]
There is an existing feature called line-sheet accessible through: /line-sheer/<season nid> 
Item variant that are marked 'add to line sheet' should appear there.

Also add the flag button to the item list in the season page.

**Comment by Moo64c** [comment]
Missing: add to migrate item variants' flags (see line 531 in garmentbox_migrate.migrate.inc).

**Comment by Moo64c** [comment]
Closed, see #120.
